#cloud-config
package_update: true
package_upgrade: true
packages:
  - git
  - make
  - curl
  - build-essential
runcmd:
  - snap install go --classic
  - snap install kubectl --classic
  - [ sh, -c, "echo 'export PATH=$PATH:/snap/bin' >> /home/ubuntu/.bashrc" ]
