package vault

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestResolveSelectedSections(t *testing.T) {
	t.Run("given all=true then returns all sections", func(t *testing.T) {
		result, err := resolveSelectedSections(nil, true)
		require.NoError(t, err)
		assert.Len(t, result, len(templateSections))
	})

	t.Run("given empty keys then returns all sections", func(t *testing.T) {
		result, err := resolveSelectedSections([]string{}, false)
		require.NoError(t, err)
		assert.Len(t, result, len(templateSections))
	})

	t.Run("given valid key then returns matching section", func(t *testing.T) {
		result, err := resolveSelectedSections([]string{"secrets"}, false)
		require.NoError(t, err)
		require.Len(t, result, 1)
		assert.Equal(t, "secrets", result[0].key)
	})

	t.Run("given multiple valid keys then returns them in order", func(t *testing.T) {
		result, err := resolveSelectedSections([]string{"kubernetes", "secrets"}, false)
		require.NoError(t, err)
		require.Len(t, result, 2)
		assert.Equal(t, "kubernetes", result[0].key)
		assert.Equal(t, "secrets", result[1].key)
	})

	t.Run("given unknown key then returns error", func(t *testing.T) {
		_, err := resolveSelectedSections([]string{"nonexistent"}, false)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "nonexistent")
	})

	t.Run("given key with whitespace then trims and resolves", func(t *testing.T) {
		result, err := resolveSelectedSections([]string{"  engines  "}, false)
		require.NoError(t, err)
		require.Len(t, result, 1)
		assert.Equal(t, "engines", result[0].key)
	})
}

func TestBuildManifest(t *testing.T) {
	t.Run("given sections then includes header", func(t *testing.T) {
		out := buildManifest(templateSections[:1])
		assert.True(t, strings.HasPrefix(out, "# Generated by:"), "expected header comment")
	})

	t.Run("given section then includes its yaml content", func(t *testing.T) {
		sections := []templateSection{{key: "test", desc: "test desc", yaml: "test: value\n"}}
		out := buildManifest(sections)
		assert.Contains(t, out, "test: value")
		assert.Contains(t, out, "TEST")
		assert.Contains(t, out, "test desc")
	})

	t.Run("given multiple sections then separates them with newlines", func(t *testing.T) {
		out := buildManifest(templateSections)
		assert.True(t, strings.Count(out, "# ==========") == len(templateSections))
	})

	t.Run("given empty sections then returns header only", func(t *testing.T) {
		out := buildManifest(nil)
		assert.True(t, strings.HasPrefix(out, "# Generated by:"))
		assert.NotContains(t, out, "# ==========")
	})
}

func TestNewGenerateManifestCmd(t *testing.T) {
	t.Run("must return non-nil command", func(t *testing.T) {
		cmd := NewGenerateManifestCmd()
		require.NotNil(t, cmd)
		assert.Equal(t, "generate-manifest", cmd.Use)
	})

	t.Run("given --all flag then prints all sections to stdout", func(t *testing.T) {
		cmd := NewGenerateManifestCmd()
		cmd.SetArgs([]string{"--all"})

		var buf strings.Builder
		cmd.SetOut(&buf)

		err := cmd.Execute()
		require.NoError(t, err)
	})

	t.Run("given --sections flag then only includes selected sections", func(t *testing.T) {
		orig := NewGenerateManifestCmdFunc
		defer func() { NewGenerateManifestCmdFunc = orig }()

		cmd := NewGenerateManifestCmd()
		cmd.SetArgs([]string{"--sections", "secrets"})

		var buf strings.Builder
		cmd.SetOut(&buf)
		cmd.SetErr(&buf)

		err := cmd.Execute()
		require.NoError(t, err)
	})

	t.Run("given --output flag then writes to file", func(t *testing.T) {
		dir := t.TempDir()
		outFile := filepath.Join(dir, "manifest.yaml")

		cmd := NewGenerateManifestCmd()
		cmd.SetArgs([]string{"--all", "--output", outFile})

		err := cmd.Execute()
		require.NoError(t, err)

		data, err := os.ReadFile(outFile)
		require.NoError(t, err)
		assert.True(t, strings.HasPrefix(string(data), "# Generated by:"))
	})

	t.Run("given unknown section then returns error", func(t *testing.T) {
		cmd := NewGenerateManifestCmd()
		cmd.SetArgs([]string{"--sections", "invalid-section"})

		var buf strings.Builder
		cmd.SetErr(&buf)

		err := cmd.Execute()
		require.Error(t, err)
	})
}

func TestTemplateSectionsCompleteness(t *testing.T) {
	t.Run("all sections have non-empty key, desc, and yaml", func(t *testing.T) {
		for _, s := range templateSections {
			assert.NotEmpty(t, s.key, "section key must not be empty")
			assert.NotEmpty(t, s.desc, "section desc must not be empty")
			assert.NotEmpty(t, s.yaml, "section yaml must not be empty")
		}
	})

	t.Run("kubernetes section exists and contains expected fields", func(t *testing.T) {
		var k8sSection *templateSection
		for i := range templateSections {
			if templateSections[i].key == "kubernetes" {
				k8sSection = &templateSections[i]
				break
			}
		}
		require.NotNil(t, k8sSection, "kubernetes section must exist")
		assert.Contains(t, k8sSection.yaml, "namespaces:")
		assert.Contains(t, k8sSection.yaml, "registry_secrets:")
		assert.Contains(t, k8sSection.yaml, "service_accounts:")
		assert.Contains(t, k8sSection.yaml, "config_maps:")
	})

	t.Run("secrets section exists and contains expected fields", func(t *testing.T) {
		var sec *templateSection
		for i := range templateSections {
			if templateSections[i].key == "secrets" {
				sec = &templateSections[i]
				break
			}
		}
		require.NotNil(t, sec, "secrets section must exist")
		assert.Contains(t, sec.yaml, "path:")
		assert.Contains(t, sec.yaml, "add:")
	})
}
