package backup

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

func backupMySQL(flags *BackupFlags, timestamp string) error {
	ctx := context.Background()

	connStr := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s",
		flags.AdminUser, flags.AdminPassword, flags.Host, flags.Port, flags.Database)

	db, err := sql.Open("mysql", connStr)
	if err != nil {
		return fmt.Errorf("failed to open connection: %w", err)
	}
	defer func() { _ = db.Close() }()

	if err := db.PingContext(ctx); err != nil {
		return fmt.Errorf("failed to connect to MySQL at %s:%d: %w", flags.Host, flags.Port, err)
	}

	outputFile := filepath.Join(flags.OutputDir, fmt.Sprintf("%s_%s.sql", flags.Database, timestamp))
	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer func() { _ = f.Close() }()

	fmt.Printf("🗄️  Backing up MySQL database '%s'...\n", flags.Database)
	fmt.Printf("   Host: %s:%d\n", flags.Host, flags.Port)
	fmt.Printf("   Output: %s\n\n", outputFile)

	fmt.Fprintf(f, "-- MySQL backup of database: %s\n", flags.Database)
	fmt.Fprintf(f, "-- Generated by stackctl on %s\n\n", time.Now().Format(time.RFC3339))
	fmt.Fprintf(f, "SET FOREIGN_KEY_CHECKS=0;\n")
	fmt.Fprintf(f, "SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';\n\n")
	fmt.Fprintf(f, "CREATE DATABASE IF NOT EXISTS `%s`;\n", flags.Database)
	fmt.Fprintf(f, "USE `%s`;\n\n", flags.Database)

	tables, err := mysqlListTables(ctx, db)
	if err != nil {
		return fmt.Errorf("failed to list tables: %w", err)
	}

	for _, table := range tables {
		if err := mysqlWriteCreateTable(ctx, db, f, table); err != nil {
			return fmt.Errorf("failed to write schema for table %s: %w", table, err)
		}
		if err := mysqlWriteTableData(ctx, db, f, table); err != nil {
			return fmt.Errorf("failed to write data for table %s: %w", table, err)
		}
	}

	fmt.Fprintf(f, "SET FOREIGN_KEY_CHECKS=1;\n")

	printBackupSuccess(outputFile)
	return nil
}

func mysqlListTables(ctx context.Context, db *sql.DB) ([]string, error) {
	rows, err := db.QueryContext(ctx, "SHOW TABLES")
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		tables = append(tables, name)
	}
	return tables, rows.Err()
}

func mysqlWriteCreateTable(ctx context.Context, db *sql.DB, w io.Writer, table string) error {
	var tableName, createSQL string
	row := db.QueryRowContext(ctx, fmt.Sprintf("SHOW CREATE TABLE `%s`", table))
	if err := row.Scan(&tableName, &createSQL); err != nil {
		return err
	}

	fmt.Fprintf(w, "--\n-- Table: %s\n--\n", table)
	fmt.Fprintf(w, "DROP TABLE IF EXISTS `%s`;\n", table)
	fmt.Fprintf(w, "%s;\n\n", createSQL)
	return nil
}

func mysqlWriteTableData(ctx context.Context, db *sql.DB, w io.Writer, table string) error {
	rows, err := db.QueryContext(ctx, fmt.Sprintf("SELECT * FROM `%s`", table))
	if err != nil {
		return err
	}
	defer func() { _ = rows.Close() }()

	cols, err := rows.Columns()
	if err != nil {
		return err
	}
	if len(cols) == 0 {
		return nil
	}

	fmt.Fprintf(w, "-- Data for table: %s\n", table)

	backtickCols := make([]string, len(cols))
	for i, c := range cols {
		backtickCols[i] = "`" + c + "`"
	}

	vals := make([]interface{}, len(cols))
	ptrs := make([]interface{}, len(cols))
	for i := range vals {
		ptrs[i] = &vals[i]
	}

	for rows.Next() {
		if err := rows.Scan(ptrs...); err != nil {
			return err
		}
		formatted := make([]string, len(vals))
		for i, v := range vals {
			formatted[i] = mysqlFormatValue(v)
		}
		fmt.Fprintf(w, "INSERT INTO `%s` (%s) VALUES (%s);\n",
			table,
			strings.Join(backtickCols, ", "),
			strings.Join(formatted, ", "))
	}

	fmt.Fprintln(w)
	return rows.Err()
}

func mysqlFormatValue(v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case bool:
		if val {
			return "1"
		}
		return "0"
	case int64:
		return strconv.FormatInt(val, 10)
	case uint64:
		return strconv.FormatUint(val, 10)
	case float64:
		return strconv.FormatFloat(val, 'f', -1, 64)
	case []byte:
		s := string(val)
		s = strings.ReplaceAll(s, "\\", "\\\\")
		s = strings.ReplaceAll(s, "'", "\\'")
		s = strings.ReplaceAll(s, "\n", "\\n")
		s = strings.ReplaceAll(s, "\r", "\\r")
		s = strings.ReplaceAll(s, "\x00", "\\0")
		return "'" + s + "'"
	case string:
		s := strings.ReplaceAll(val, "\\", "\\\\")
		s = strings.ReplaceAll(s, "'", "\\'")
		s = strings.ReplaceAll(s, "\n", "\\n")
		s = strings.ReplaceAll(s, "\r", "\\r")
		s = strings.ReplaceAll(s, "\x00", "\\0")
		return "'" + s + "'"
	case time.Time:
		return "'" + val.Format("2006-01-02 15:04:05") + "'"
	default:
		return "'" + strings.ReplaceAll(fmt.Sprintf("%v", val), "'", "\\'") + "'"
	}
}
