package backup

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	_ "github.com/lib/pq"
)

func backupPostgres(flags *BackupFlags, timestamp string) error {
	ctx := context.Background()

	connStr := fmt.Sprintf("postgres://%s:%s@%s:%d/%s?sslmode=disable",
		flags.AdminUser, flags.AdminPassword, flags.Host, flags.Port, flags.Database)

	db, err := sql.Open("postgres", connStr)
	if err != nil {
		return fmt.Errorf("failed to open connection: %w", err)
	}
	defer func() { _ = db.Close() }()

	if err := db.PingContext(ctx); err != nil {
		return fmt.Errorf("failed to connect to PostgreSQL at %s:%d: %w", flags.Host, flags.Port, err)
	}

	outputFile := filepath.Join(flags.OutputDir, fmt.Sprintf("%s_%s.sql", flags.Database, timestamp))
	f, err := os.Create(outputFile)
	if err != nil {
		return fmt.Errorf("failed to create output file: %w", err)
	}
	defer func() { _ = f.Close() }()

	fmt.Printf("🗄️  Backing up PostgreSQL database '%s'...\n", flags.Database)
	fmt.Printf("   Host: %s:%d\n", flags.Host, flags.Port)
	fmt.Printf("   Output: %s\n\n", outputFile)

	_, _ = fmt.Fprintf(f, "-- PostgreSQL backup of database: %s\n", flags.Database)
	_, _ = fmt.Fprintf(f, "-- Generated by stackctl on %s\n\n", time.Now().Format(time.RFC3339))
	_, _ = fmt.Fprintf(f, "SET client_encoding = 'UTF8';\n")
	_, _ = fmt.Fprintf(f, "SET standard_conforming_strings = on;\n\n")

	tables, err := pgListTables(ctx, db)
	if err != nil {
		return fmt.Errorf("failed to list tables: %w", err)
	}

	for _, table := range tables {
		if err := pgWriteCreateTable(ctx, db, f, table); err != nil {
			return fmt.Errorf("failed to write schema for table %s: %w", table, err)
		}
		if err := pgWriteTableData(ctx, db, f, table); err != nil {
			return fmt.Errorf("failed to write data for table %s: %w", table, err)
		}
	}

	if err := pgWriteIndexes(ctx, db, f, tables); err != nil {
		return fmt.Errorf("failed to write indexes: %w", err)
	}

	if err := pgWriteSequences(ctx, db, f); err != nil {
		return fmt.Errorf("failed to write sequences: %w", err)
	}

	printBackupSuccess(outputFile)
	return nil
}

func pgListTables(ctx context.Context, db *sql.DB) ([]string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT table_name FROM information_schema.tables
		WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
		ORDER BY table_name`)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var tables []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		tables = append(tables, name)
	}
	return tables, rows.Err()
}

func pgWriteCreateTable(ctx context.Context, db *sql.DB, w io.Writer, table string) error {
	rows, err := db.QueryContext(ctx, `
		SELECT column_name, data_type, character_maximum_length,
		       numeric_precision, numeric_scale, is_nullable, column_default, udt_name
		FROM information_schema.columns
		WHERE table_schema = 'public' AND table_name = $1
		ORDER BY ordinal_position`, table)
	if err != nil {
		return err
	}
	defer func() { _ = rows.Close() }()

	type columnDef struct {
		name       string
		dataType   string
		maxLen     sql.NullInt64
		numPrec    sql.NullInt64
		numScale   sql.NullInt64
		nullable   string
		defaultVal sql.NullString
		udtName    string
	}

	var cols []columnDef
	for rows.Next() {
		var c columnDef
		if err := rows.Scan(&c.name, &c.dataType, &c.maxLen, &c.numPrec, &c.numScale,
			&c.nullable, &c.defaultVal, &c.udtName); err != nil {
			return err
		}
		cols = append(cols, c)
	}
	if err := rows.Err(); err != nil {
		return err
	}

	pkCols, err := pgGetPrimaryKeys(ctx, db, table)
	if err != nil {
		return err
	}
	pkSet := make(map[string]bool, len(pkCols))
	for _, c := range pkCols {
		pkSet[c] = true
	}

	_, _ = fmt.Fprintf(w, "--\n-- Table: %s\n--\n", table)
	_, _ = fmt.Fprintf(w, "DROP TABLE IF EXISTS %q CASCADE;\n", table)
	_, _ = fmt.Fprintf(w, "CREATE TABLE %q (\n", table)

	var colDefs []string
	for _, c := range cols {
		sqlType := pgColumnType(c.dataType, c.maxLen, c.numPrec, c.numScale, c.udtName, c.defaultVal)
		def := fmt.Sprintf("    %q %s", c.name, sqlType)
		if c.nullable == "NO" {
			def += " NOT NULL"
		}
		if c.defaultVal.Valid && !strings.Contains(c.defaultVal.String, "nextval") {
			def += " DEFAULT " + c.defaultVal.String
		}
		colDefs = append(colDefs, def)
	}

	if len(pkCols) > 0 {
		quoted := make([]string, len(pkCols))
		for i, c := range pkCols {
			quoted[i] = fmt.Sprintf("%q", c)
		}
		colDefs = append(colDefs, fmt.Sprintf("    PRIMARY KEY (%s)", strings.Join(quoted, ", ")))
	}

	_, _ = fmt.Fprintf(w, "%s\n);\n\n", strings.Join(colDefs, ",\n"))
	return nil
}

func pgColumnType(dataType string, maxLen, numPrec, numScale sql.NullInt64, udtName string, defVal sql.NullString) string {
	switch dataType {
	case "character varying":
		if maxLen.Valid {
			return fmt.Sprintf("VARCHAR(%d)", maxLen.Int64)
		}
		return "TEXT"
	case "character":
		if maxLen.Valid {
			return fmt.Sprintf("CHAR(%d)", maxLen.Int64)
		}
		return "CHAR"
	case "numeric", "decimal":
		if numPrec.Valid && numScale.Valid {
			return fmt.Sprintf("NUMERIC(%d,%d)", numPrec.Int64, numScale.Int64)
		}
		return "NUMERIC"
	case "integer":
		if defVal.Valid && strings.Contains(defVal.String, "nextval") {
			return "SERIAL"
		}
		return "INTEGER"
	case "bigint":
		if defVal.Valid && strings.Contains(defVal.String, "nextval") {
			return "BIGSERIAL"
		}
		return "BIGINT"
	case "smallint":
		return "SMALLINT"
	case "real":
		return "REAL"
	case "double precision":
		return "DOUBLE PRECISION"
	case "boolean":
		return "BOOLEAN"
	case "text":
		return "TEXT"
	case "bytea":
		return "BYTEA"
	case "uuid":
		return "UUID"
	case "json":
		return "JSON"
	case "jsonb":
		return "JSONB"
	case "date":
		return "DATE"
	case "time without time zone":
		return "TIME"
	case "time with time zone":
		return "TIMETZ"
	case "timestamp without time zone":
		return "TIMESTAMP"
	case "timestamp with time zone":
		return "TIMESTAMPTZ"
	case "interval":
		return "INTERVAL"
	case "ARRAY":
		return udtName + "[]"
	case "USER-DEFINED":
		return udtName
	default:
		return strings.ToUpper(dataType)
	}
}

func pgGetPrimaryKeys(ctx context.Context, db *sql.DB, table string) ([]string, error) {
	rows, err := db.QueryContext(ctx, `
		SELECT kcu.column_name
		FROM information_schema.key_column_usage kcu
		JOIN information_schema.table_constraints tc
		    ON tc.constraint_name = kcu.constraint_name
		    AND tc.table_schema = kcu.table_schema
		WHERE tc.constraint_type = 'PRIMARY KEY'
		    AND kcu.table_schema = 'public'
		    AND kcu.table_name = $1
		ORDER BY kcu.ordinal_position`, table)
	if err != nil {
		return nil, err
	}
	defer func() { _ = rows.Close() }()

	var cols []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		cols = append(cols, name)
	}
	return cols, rows.Err()
}

func pgWriteTableData(ctx context.Context, db *sql.DB, w io.Writer, table string) error {
	rows, err := db.QueryContext(ctx, fmt.Sprintf(`SELECT * FROM %q`, table))
	if err != nil {
		return err
	}
	defer func() { _ = rows.Close() }()

	cols, err := rows.Columns()
	if err != nil {
		return err
	}
	if len(cols) == 0 {
		return nil
	}

	_, _ = fmt.Fprintf(w, "-- Data for table: %s\n", table)

	quotedCols := make([]string, len(cols))
	for i, c := range cols {
		quotedCols[i] = fmt.Sprintf("%q", c)
	}

	vals := make([]interface{}, len(cols))
	ptrs := make([]interface{}, len(cols))
	for i := range vals {
		ptrs[i] = &vals[i]
	}

	for rows.Next() {
		if err := rows.Scan(ptrs...); err != nil {
			return err
		}
		formatted := make([]string, len(vals))
		for i, v := range vals {
			formatted[i] = pgFormatValue(v)
		}
		_, _ = fmt.Fprintf(w, "INSERT INTO %q (%s) VALUES (%s);\n",
			table,
			strings.Join(quotedCols, ", "),
			strings.Join(formatted, ", "))
	}

	_, _ = fmt.Fprintln(w)
	return rows.Err()
}

func pgFormatValue(v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case bool:
		if val {
			return "TRUE"
		}
		return "FALSE"
	case int64:
		return strconv.FormatInt(val, 10)
	case float64:
		return strconv.FormatFloat(val, 'f', -1, 64)
	case []byte:
		return "'" + strings.ReplaceAll(string(val), "'", "''") + "'"
	case string:
		return "'" + strings.ReplaceAll(val, "'", "''") + "'"
	case time.Time:
		return "'" + val.Format("2006-01-02 15:04:05.999999-07:00") + "'"
	default:
		return "'" + strings.ReplaceAll(fmt.Sprintf("%v", val), "'", "''") + "'"
	}
}

func pgWriteIndexes(ctx context.Context, db *sql.DB, w io.Writer, tables []string) error {
	if len(tables) == 0 {
		return nil
	}

	placeholders := make([]string, len(tables))
	args := make([]interface{}, len(tables))
	for i, t := range tables {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
		args[i] = t
	}

	query := fmt.Sprintf(`
		SELECT tablename, indexname, indexdef
		FROM pg_indexes
		WHERE schemaname = 'public'
		  AND tablename IN (%s)
		  AND indexname NOT IN (
		      SELECT constraint_name FROM information_schema.table_constraints
		      WHERE constraint_type = 'PRIMARY KEY' AND table_schema = 'public'
		  )
		ORDER BY tablename, indexname`, strings.Join(placeholders, ", "))

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return err
	}
	defer func() { _ = rows.Close() }()

	_, _ = fmt.Fprintf(w, "-- Indexes\n")
	for rows.Next() {
		var tableName, indexName, indexDef string
		if err := rows.Scan(&tableName, &indexName, &indexDef); err != nil {
			return err
		}
		_, _ = fmt.Fprintf(w, "%s;\n", indexDef)
	}
	_, _ = fmt.Fprintln(w)
	return rows.Err()
}

func pgWriteSequences(ctx context.Context, db *sql.DB, w io.Writer) error {
	rows, err := db.QueryContext(ctx, `
		SELECT sequence_name, last_value
		FROM pg_sequences
		WHERE schemaname = 'public'`)
	if err != nil {
		return err
	}
	defer func() { _ = rows.Close() }()

	_, _ = fmt.Fprintf(w, "-- Sequences\n")
	for rows.Next() {
		var name string
		var lastVal sql.NullInt64
		if err := rows.Scan(&name, &lastVal); err != nil {
			return err
		}
		if lastVal.Valid {
			_, _ = fmt.Fprintf(w, "SELECT setval('%s', %d);\n", name, lastVal.Int64)
		}
	}
	_, _ = fmt.Fprintln(w)
	return rows.Err()
}
